name: Download ECB data

on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:

concurrency:
  group: "download-ecb"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  download:
    name: "Download ECB exchange rates"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Download ECB daily
        run: wget https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml -O ecb-daily.xml
      - name: Download ECB last 90 days
        run: wget https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist-90d.xml -O ecb-historic-90d.xml
      - name: Download ECB historic
        run: wget https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist.xml -O ecb-historic.xml
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updated exchange rate data from ECB
